CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    user_type VARCHAR(20) NOT NULL DEFAULT 'user',
    birthdate DATE,
    gender VARCHAR(10),
    country VARCHAR(100),
    municipality VARCHAR(100),
    address VARCHAR(255),
    job VARCHAR(100),
    lat DECIMAL(10,8),
    lon DECIMAL(11,8),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (
    username, password, user_type, birthdate, gender,
    country, municipality, address, job, lat, lon,
    created_at, updated_at
)
SELECT
    'admin',
    'admin123!',
    'admin',
    DATE '1990-01-15',
    'MALE',
    'Greece',
    'Athens',
    '123 Main Street, Athens 10434',
    'System Administrator',
    37.983810,
    23.727539,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM users WHERE username = 'admin'
);

COMMIT;
