CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    telephone VARCHAR(50),
    password VARCHAR(255) NOT NULL,
    user_type VARCHAR(20) NOT NULL DEFAULT 'USER',
    birthdate DATE,
    gender VARCHAR(10),
    country VARCHAR(100),
    municipality VARCHAR(100),
    address VARCHAR(255),
    job VARCHAR(100),
    volunteer_role VARCHAR(20),
    lat DECIMAL(10,8),
    lon DECIMAL(11,8),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_code VARCHAR(50) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    description CLOB,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    priority VARCHAR(20) NOT NULL DEFAULT 'medium',
    location VARCHAR(255),
    lat DECIMAL(10,8),
    lon DECIMAL(11,8),
    needed_drivers INT DEFAULT 0,
    needed_firefighters INT DEFAULT 0,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_incidents_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(100),
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_participants_incident FOREIGN KEY (incident_id) REFERENCES incidents(id),
    CONSTRAINT fk_participants_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT,
    sender_id BIGINT,
    receiver_id BIGINT,
    title VARCHAR(255) NOT NULL,
    content CLOB NOT NULL,
    message_type VARCHAR(30) NOT NULL DEFAULT 'public' CHECK (message_type IN ('public', 'private')),
    priority VARCHAR(20) NOT NULL DEFAULT 'normal',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_incident FOREIGN KEY (incident_id) REFERENCES incidents(id),
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id),
    CONSTRAINT fk_messages_receiver FOREIGN KEY (receiver_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS participant_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    requested_role VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'requested',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    decided_at TIMESTAMP,
    decided_by BIGINT,
    CONSTRAINT fk_participant_requests_incident FOREIGN KEY (incident_id) REFERENCES incidents(id),
    CONSTRAINT fk_participant_requests_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_participant_requests_decider FOREIGN KEY (decided_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS notification_reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    notification_id VARCHAR(120) NOT NULL,
    read_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_reads_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_notification_reads_user_notification UNIQUE (user_id, notification_id)
);

-- Compatibility updates for older snapshots
ALTER TABLE incidents ALTER COLUMN latitude RENAME TO lat;
ALTER TABLE incidents ALTER COLUMN longitude RENAME TO lon;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS lat DECIMAL(10,8);
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS lon DECIMAL(11,8);
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS needed_drivers INT DEFAULT 0;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS needed_firefighters INT DEFAULT 0;

ALTER TABLE participants ALTER COLUMN status RENAME TO role;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS role VARCHAR(100);

ALTER TABLE messages ALTER COLUMN content_clob RENAME TO content;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS content CLOB;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS receiver_id BIGINT;

ALTER TABLE participant_requests ADD COLUMN IF NOT EXISTS requested_role VARCHAR(100);
ALTER TABLE participant_requests ADD COLUMN IF NOT EXISTS status VARCHAR(30);
ALTER TABLE participant_requests ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE participant_requests ADD COLUMN IF NOT EXISTS decided_at TIMESTAMP;
ALTER TABLE participant_requests ADD COLUMN IF NOT EXISTS decided_by BIGINT;
ALTER TABLE notification_reads ADD COLUMN IF NOT EXISTS read_at TIMESTAMP;

ALTER TABLE users ADD COLUMN IF NOT EXISTS volunteer_role VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS telephone VARCHAR(50);

UPDATE users SET user_type = UPPER(user_type) WHERE user_type IS NOT NULL;
UPDATE users SET user_type = 'USER'
WHERE user_type IS NULL OR user_type NOT IN ('ADMIN', 'USER', 'VOLUNTEER');
UPDATE users SET volunteer_role = UPPER(volunteer_role) WHERE volunteer_role IS NOT NULL;
UPDATE users SET volunteer_role = NULL WHERE user_type IN ('ADMIN', 'USER');
UPDATE users SET volunteer_role = 'FIREFIGHTER' WHERE user_type = 'VOLUNTEER' AND (volunteer_role IS NULL OR volunteer_role NOT IN ('FIREFIGHTER', 'DRIVER'));

MERGE INTO users (
    username, first_name, last_name, telephone, password, user_type, birthdate, gender,
    country, municipality, address, job, volunteer_role, lat, lon, created_at, updated_at
) KEY (username) VALUES
    ('admin', 'System', 'Admin', '+30-210-0000001', 'admin123!', 'ADMIN', DATE '1990-01-15', 'MALE', 'Greece', 'Athens', '123 Main Street', 'System Administrator', NULL, 37.983810, 23.727539, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('simple_user_1', 'Nikos', 'Papadopoulos', '+30-210-0000002', 'user123!', 'USER', DATE '1997-06-11', 'MALE', 'Greece', 'Athens', 'Kolonaki 12', 'Citizen', NULL, 37.977650, 23.744820, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('simple_user_2', 'Eleni', 'Karagianni', '+30-210-0000003', 'user123!', 'USER', DATE '1993-03-22', 'FEMALE', 'Greece', 'Piraeus', 'Akti Miaouli 51', 'Citizen', NULL, 37.941640, 23.652390, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('simple_user_3', 'Giorgos', 'Kostas', '+30-210-0000004', 'user123!', 'USER', DATE '1989-07-19', 'MALE', 'Greece', 'Marousi', 'Kifisias 80', 'Citizen', NULL, 38.045500, 23.805500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('simple_user_4', 'Maria', 'Antonopoulou', '+30-210-0000005', 'user123!', 'USER', DATE '1999-11-05', 'FEMALE', 'Greece', 'Glyfada', 'Poseidonos 22', 'Citizen', NULL, 37.864000, 23.748000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('volunteer_maria', 'Maria', 'Dimitriou', '+30-210-0000006', 'vol123!', 'VOLUNTEER', DATE '1995-10-08', 'FEMALE', 'Greece', 'Athens', 'Kifisias Ave 25', 'Volunteer Firefighter', 'FIREFIGHTER', 38.025170, 23.793410, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('volunteer_nikos', 'Nikos', 'Alexiou', '+30-210-0000007', 'vol123!', 'VOLUNTEER', DATE '1991-12-14', 'MALE', 'Greece', 'Peristeri', 'Ethnikis Antistaseos 9', 'Volunteer Responder', 'DRIVER', 38.015390, 23.691870, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('volunteer_alex', 'Alex', 'Petrou', '+30-210-0000008', 'vol123!', 'VOLUNTEER', DATE '1994-04-20', 'MALE', 'Greece', 'Kallithea', 'Thiseos 54', 'Volunteer Driver', 'DRIVER', 37.960250, 23.697600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('volunteer_eleni', 'Eleni', 'Sarris', '+30-210-0000009', 'vol123!', 'VOLUNTEER', DATE '1996-08-28', 'FEMALE', 'Greece', 'Nikaia', 'Petrou Ralli 18', 'Volunteer Firefighter', 'FIREFIGHTER', 37.970900, 23.640600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

UPDATE users SET user_type = 'ADMIN' WHERE LOWER(username) = 'admin';

-- Core fixed incidents
INSERT INTO incidents (incident_code, title, description, status, priority, location, lat, lon, needed_drivers, needed_firefighters, created_by, created_at, updated_at)
SELECT 'INC-1001', 'Warehouse Smoke Alert', 'Smoke reported from a storage warehouse.', 'active', 'high', 'Metaxourgeio, Athens', 37.984900, 23.718100, 2, 4, (SELECT id FROM users WHERE username = 'admin'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM incidents WHERE incident_code = 'INC-1001');

INSERT INTO incidents (incident_code, title, description, status, priority, location, lat, lon, needed_drivers, needed_firefighters, created_by, created_at, updated_at)
SELECT 'INC-1002', 'Forest Edge Fire', 'Small fire near forest edge.', 'active', 'medium', 'Dionysos, Attica', 38.108400, 23.889200, 1, 6, (SELECT id FROM users WHERE username = 'admin'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM incidents WHERE incident_code = 'INC-1002');

INSERT INTO incidents (incident_code, title, description, status, priority, location, lat, lon, needed_drivers, needed_firefighters, created_by, created_at, updated_at)
SELECT 'INC-1003', 'Minor Vehicle Fire', 'Vehicle fire resolved with no injuries.', 'resolved', 'low', 'Nea Smyrni, Athens', 37.947600, 23.713900, 1, 2, (SELECT id FROM users WHERE username = 'admin'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM incidents WHERE incident_code = 'INC-1003');

-- Bulk incidents for testing (26 rows: INC-2001..INC-2026)
INSERT INTO incidents (incident_code, title, description, status, priority, location, lat, lon, needed_drivers, needed_firefighters, created_by, created_at, updated_at)
SELECT
    'INC-' || CAST(2000 + X AS VARCHAR),
    'Test Incident ' || CAST(X AS VARCHAR),
    'Generated incident #' || CAST(X AS VARCHAR) || ' for dashboard and map testing.',
    CASE
        WHEN MOD(X, 7) = 0 THEN 'requested'
        WHEN MOD(X, 3) = 0 THEN 'resolved'
        ELSE 'active'
    END,
    CASE
        WHEN MOD(X, 4) = 0 THEN 'high'
        WHEN MOD(X, 2) = 0 THEN 'medium'
        ELSE 'low'
    END,
    'Sector ' || CAST(X AS VARCHAR) || ', Athens',
    37.900000 + (X * 0.004000),
    23.600000 + (X * 0.005000),
    1 + MOD(X, 3),
    2 + MOD(X, 5),
    CASE
        WHEN MOD(X, 9) = 0 THEN (SELECT id FROM users WHERE username = 'simple_user_1')
        WHEN MOD(X, 8) = 0 THEN (SELECT id FROM users WHERE username = 'simple_user_2')
        ELSE (SELECT id FROM users WHERE username = 'admin')
    END,
    DATEADD('HOUR', -X, CURRENT_TIMESTAMP),
    DATEADD('HOUR', -X + 1, CURRENT_TIMESTAMP)
FROM SYSTEM_RANGE(1, 26)
WHERE NOT EXISTS (
    SELECT 1
    FROM incidents i
    WHERE i.incident_code = 'INC-' || CAST(2000 + X AS VARCHAR)
);

-- Participant seeds (30+ potential rows depending on existing data)
INSERT INTO participants (incident_id, user_id, role, joined_at)
SELECT i.id, u.id, 'Firefighter', CURRENT_TIMESTAMP
FROM incidents i
JOIN users u ON u.username = 'volunteer_maria'
WHERE LOWER(i.status) IN ('active', 'resolved')
  AND i.incident_code LIKE 'INC-20%'
  AND MOD(i.id, 2) = 0
  AND NOT EXISTS (SELECT 1 FROM participants p WHERE p.incident_id = i.id AND p.user_id = u.id);

INSERT INTO participants (incident_id, user_id, role, joined_at)
SELECT i.id, u.id, 'Driver', CURRENT_TIMESTAMP
FROM incidents i
JOIN users u ON u.username = 'volunteer_nikos'
WHERE LOWER(i.status) IN ('active', 'resolved')
  AND i.incident_code LIKE 'INC-20%'
  AND MOD(i.id, 2) = 1
  AND NOT EXISTS (SELECT 1 FROM participants p WHERE p.incident_id = i.id AND p.user_id = u.id);

INSERT INTO participants (incident_id, user_id, role, joined_at)
SELECT i.id, u.id, 'Firefighter', CURRENT_TIMESTAMP
FROM incidents i
JOIN users u ON u.username = 'volunteer_eleni'
WHERE LOWER(i.status) = 'active'
  AND i.incident_code LIKE 'INC-20%'
  AND MOD(i.id, 3) = 0
  AND NOT EXISTS (SELECT 1 FROM participants p WHERE p.incident_id = i.id AND p.user_id = u.id);

INSERT INTO participants (incident_id, user_id, role, joined_at)
SELECT i.id, u.id, 'Observer', CURRENT_TIMESTAMP
FROM incidents i
JOIN users u ON u.username = 'simple_user_1'
WHERE LOWER(i.status) IN ('active', 'resolved')
  AND i.incident_code LIKE 'INC-20%'
  AND MOD(i.id, 5) = 0
  AND NOT EXISTS (SELECT 1 FROM participants p WHERE p.incident_id = i.id AND p.user_id = u.id);

-- Message seeds (30+)
INSERT INTO messages (incident_id, sender_id, receiver_id, title, content, message_type, priority, created_at)
SELECT i.id, u.id, NULL, 'Update for ' || i.incident_code, 'Response teams assigned and monitoring scene.', 'public', 'normal', CURRENT_TIMESTAMP
FROM incidents i
JOIN users u ON u.username = 'admin'
WHERE i.incident_code LIKE 'INC-20%'
  AND NOT EXISTS (
      SELECT 1 FROM messages m WHERE m.incident_id = i.id AND m.title = 'Update for ' || i.incident_code
  );

INSERT INTO messages (incident_id, sender_id, receiver_id, title, content, message_type, priority, created_at)
SELECT i.id, u.id, NULL, 'Incident Request ' || i.incident_code, 'New incident request waiting for admin action.', 'public', 'normal', CURRENT_TIMESTAMP
FROM incidents i
JOIN users u ON u.username = 'admin'
WHERE LOWER(i.status) = 'requested'
  AND i.incident_code LIKE 'INC-20%'
  AND NOT EXISTS (
      SELECT 1 FROM messages m WHERE m.incident_id = i.id AND m.title = 'Incident Request ' || i.incident_code
  );

INSERT INTO messages (incident_id, sender_id, receiver_id, title, content, message_type, priority, created_at)
SELECT NULL, u.id, NULL, 'Shift Reminder', 'Please check assignments and readiness before duty.', 'public', 'normal', CURRENT_TIMESTAMP
FROM users u
WHERE u.username = 'admin'
  AND NOT EXISTS (
      SELECT 1 FROM messages m WHERE m.incident_id IS NULL AND m.title = 'Shift Reminder'
  );

INSERT INTO messages (incident_id, sender_id, receiver_id, title, content, message_type, priority, created_at)
SELECT NULL, u.id, NULL, 'Volunteer Coordination', 'Volunteer drivers should confirm vehicle readiness.', 'public', 'normal', CURRENT_TIMESTAMP
FROM users u
WHERE u.username = 'admin'
  AND NOT EXISTS (
      SELECT 1 FROM messages m WHERE m.incident_id IS NULL AND m.title = 'Volunteer Coordination'
  );

INSERT INTO messages (incident_id, sender_id, receiver_id, title, content, message_type, priority, created_at)
SELECT
    NULL,
    admin_user.id,
    target_user.id,
    'Private Follow Up',
    'Please check your profile details and confirm your availability.',
    'private',
    'normal',
    CURRENT_TIMESTAMP
FROM users admin_user
JOIN users target_user ON target_user.username = 'volunteer_maria'
WHERE admin_user.username = 'admin'
  AND NOT EXISTS (
      SELECT 1 FROM messages m
      WHERE m.message_type = 'private'
        AND m.sender_id = admin_user.id
        AND m.receiver_id = target_user.id
        AND m.title = 'Private Follow Up'
  );

-- Volunteer join-request seeds
INSERT INTO participant_requests (incident_id, user_id, requested_role, status, created_at, decided_at, decided_by)
SELECT i.id, u.id, 'DRIVER', 'requested', CURRENT_TIMESTAMP, NULL, NULL
FROM incidents i
JOIN users u ON u.username = 'volunteer_alex'
WHERE LOWER(i.status) = 'active'
  AND MOD(i.id, 4) = 0
  AND i.incident_code LIKE 'INC-20%'
  AND NOT EXISTS (
      SELECT 1 FROM participant_requests pr
      WHERE pr.incident_id = i.id AND pr.user_id = u.id AND LOWER(pr.status) = 'requested'
  );

INSERT INTO participant_requests (incident_id, user_id, requested_role, status, created_at, decided_at, decided_by)
SELECT i.id, u.id, 'DRIVER', 'approved', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM users WHERE username = 'admin')
FROM incidents i
JOIN users u ON u.username = 'volunteer_nikos'
WHERE LOWER(i.status) = 'resolved'
  AND MOD(i.id, 6) = 0
  AND i.incident_code LIKE 'INC-20%'
  AND NOT EXISTS (
      SELECT 1 FROM participant_requests pr
      WHERE pr.incident_id = i.id AND pr.user_id = u.id AND LOWER(pr.status) = 'approved'
  );

INSERT INTO participant_requests (incident_id, user_id, requested_role, status, created_at, decided_at, decided_by)
SELECT i.id, u.id, 'FIREFIGHTER', 'rejected', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, (SELECT id FROM users WHERE username = 'admin')
FROM incidents i
JOIN users u ON u.username = 'volunteer_eleni'
WHERE LOWER(i.status) = 'requested'
  AND MOD(i.id, 7) = 0
  AND i.incident_code LIKE 'INC-20%'
  AND NOT EXISTS (
      SELECT 1 FROM participant_requests pr
      WHERE pr.incident_id = i.id AND pr.user_id = u.id AND LOWER(pr.status) = 'rejected'
  );

-- Keep timestamps and role fields healthy
UPDATE users SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE users SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL;
UPDATE users SET volunteer_role = NULL WHERE user_type IN ('ADMIN', 'USER');
UPDATE users SET volunteer_role = 'FIREFIGHTER'
WHERE user_type = 'VOLUNTEER' AND (volunteer_role IS NULL OR volunteer_role NOT IN ('FIREFIGHTER', 'DRIVER'));
UPDATE incidents SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE incidents SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL;
UPDATE incidents SET status = LOWER(status) WHERE status IS NOT NULL;
UPDATE incidents SET status = 'requested' WHERE status = 'pending';
UPDATE incidents SET status = 'resolved' WHERE status = 'rejected';
UPDATE incidents SET status = 'requested' WHERE status IS NULL OR status NOT IN ('active', 'resolved', 'requested');
UPDATE incidents SET needed_drivers = 0 WHERE needed_drivers IS NULL OR needed_drivers < 0;
UPDATE incidents SET needed_firefighters = 0 WHERE needed_firefighters IS NULL OR needed_firefighters < 0;
UPDATE incidents
SET needed_drivers = CASE WHEN MOD(id, 2) = 0 THEN 1 ELSE 2 END,
    needed_firefighters = CASE WHEN MOD(id, 3) = 0 THEN 4 ELSE 2 END
WHERE LOWER(status) IN ('active', 'resolved', 'requested')
  AND COALESCE(needed_drivers, 0) = 0
  AND COALESCE(needed_firefighters, 0) = 0;
UPDATE participants SET joined_at = CURRENT_TIMESTAMP WHERE joined_at IS NULL;
UPDATE messages SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE messages SET message_type = LOWER(message_type) WHERE message_type IS NOT NULL;
UPDATE messages SET message_type = 'private' WHERE message_type = 'admin';
UPDATE messages SET message_type = 'public' WHERE message_type IS NULL OR message_type NOT IN ('public', 'private');
UPDATE messages
SET message_type = 'public',
    receiver_id = NULL
WHERE title = 'Volunteer Coordination'
   OR title LIKE 'Incident Pending Approval %'
   OR title LIKE 'Incident Request %';
UPDATE messages
SET message_type = 'public',
    receiver_id = NULL
WHERE message_type = 'private'
  AND sender_id IS NOT NULL
  AND sender_id = receiver_id;
UPDATE messages
SET receiver_id = COALESCE((SELECT id FROM users WHERE username = 'admin'), sender_id)
WHERE message_type = 'private'
  AND receiver_id IS NULL;
DELETE FROM messages WHERE title = 'Volunteer Request' OR title LIKE 'Volunteer Request %';
UPDATE participant_requests SET status = 'requested' WHERE status IS NULL;
UPDATE participant_requests SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE participant_requests SET requested_role = UPPER(requested_role) WHERE requested_role IS NOT NULL;
UPDATE participant_requests
SET requested_role = (
    SELECT volunteer_role
    FROM users
    WHERE users.id = participant_requests.user_id
)
WHERE user_id IN (
    SELECT id
    FROM users
    WHERE user_type = 'VOLUNTEER'
      AND volunteer_role IN ('FIREFIGHTER', 'DRIVER')
)
  AND (
      requested_role IS NULL
      OR UPPER(requested_role) <> (
          SELECT volunteer_role
          FROM users
          WHERE users.id = participant_requests.user_id
      )
  );
INSERT INTO participants (incident_id, user_id, role, joined_at)
SELECT
    pr.incident_id,
    pr.user_id,
    CASE WHEN pr.requested_role = 'DRIVER' THEN 'Driver' ELSE 'Firefighter' END,
    COALESCE(pr.decided_at, CURRENT_TIMESTAMP)
FROM participant_requests pr
WHERE LOWER(pr.status) = 'approved'
  AND pr.requested_role IN ('DRIVER', 'FIREFIGHTER')
  AND NOT EXISTS (
      SELECT 1
      FROM participants p
      WHERE p.incident_id = pr.incident_id
        AND p.user_id = pr.user_id
  );

-- Requested by product flow: clear all participation requests on startup for clean testing.
DELETE FROM participant_requests;

COMMIT;
