begin;

-- -------------------------------------------------------------------
-- FireServiceSystem - Supabase (Postgres) init + seed
-- Tables: users, incidents, participants, messages, participant_requests, notification_reads
-- -------------------------------------------------------------------

create table if not exists users (
  id bigint generated by default as identity primary key,
  username varchar(50) not null unique,
  first_name varchar(100),
  last_name varchar(100),
  telephone varchar(50),
  password varchar(255) not null,
  user_type varchar(20) not null default 'USER',
  birthdate date,
  gender varchar(10),
  country varchar(100),
  municipality varchar(100),
  address varchar(255),
  job varchar(100),
  volunteer_role varchar(20),
  lat double precision,
  lon double precision,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  constraint chk_users_user_type check (user_type in ('ADMIN','USER','VOLUNTEER')),
  constraint chk_users_volunteer_role check (volunteer_role is null or volunteer_role in ('FIREFIGHTER','DRIVER'))
);

create table if not exists incidents (
  id bigint generated by default as identity primary key,
  incident_code varchar(50) not null unique,
  title varchar(255) not null,
  description text,
  status varchar(30) not null default 'active',
  priority varchar(20) not null default 'medium',
  location varchar(255),
  lat double precision,
  lon double precision,
  needed_drivers int not null default 0,
  needed_firefighters int not null default 0,
  created_by bigint,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  constraint fk_incidents_created_by foreign key (created_by) references users(id)
);

create table if not exists participants (
  id bigint generated by default as identity primary key,
  incident_id bigint not null,
  user_id bigint not null,
  role varchar(100),
  joined_at timestamp default now(),
  constraint fk_participants_incident foreign key (incident_id) references incidents(id),
  constraint fk_participants_user foreign key (user_id) references users(id),
  constraint chk_participants_role check (upper(role) in ('FIREFIGHTER','DRIVER'))
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  incident_id bigint,
  sender_id bigint,
  receiver_id bigint,
  title varchar(255) not null,
  content text not null,
  message_type varchar(30) not null default 'public',
  priority varchar(20) not null default 'normal',
  created_at timestamp default now(),
  constraint fk_messages_incident foreign key (incident_id) references incidents(id),
  constraint fk_messages_sender foreign key (sender_id) references users(id),
  constraint fk_messages_receiver foreign key (receiver_id) references users(id),
  constraint chk_messages_type check (message_type in ('public','private'))
);

create table if not exists participant_requests (
  id bigint generated by default as identity primary key,
  incident_id bigint not null,
  user_id bigint not null,
  requested_role varchar(100) not null,
  status varchar(30) not null default 'requested',
  created_at timestamp default now(),
  decided_at timestamp,
  decided_by bigint,
  constraint fk_participant_requests_incident foreign key (incident_id) references incidents(id),
  constraint fk_participant_requests_user foreign key (user_id) references users(id),
  constraint fk_participant_requests_decider foreign key (decided_by) references users(id),
  constraint chk_participant_requests_role check (upper(requested_role) in ('FIREFIGHTER','DRIVER'))
);

create table if not exists notification_reads (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  notification_id varchar(120) not null,
  read_at timestamp default now(),
  constraint fk_notification_reads_user foreign key (user_id) references users(id),
  constraint uq_notification_reads_user_notification unique (user_id, notification_id)
);

-- -------------------------------------------------------------------
-- Seed users (same usernames as your H2 init_db.sql)
-- -------------------------------------------------------------------
insert into users (
  username, first_name, last_name, telephone, password, user_type, birthdate, gender,
  country, municipality, address, job, volunteer_role, lat, lon, created_at, updated_at
) values
  ('admin', 'System', 'Admin', '+30-210-0000001', 'admin123!', 'ADMIN', date '1990-01-15', 'MALE', 'Greece', 'Athens', '123 Main Street', 'System Administrator', null, 37.983810, 23.727539, now(), now()),
  ('simple_user_1', 'Nikos', 'Papadopoulos', '+30-210-0000002', 'user123!', 'USER', date '1997-06-11', 'MALE', 'Greece', 'Athens', 'Kolonaki 12', 'Citizen', null, 37.977650, 23.744820, now(), now()),
  ('simple_user_2', 'Eleni', 'Karagianni', '+30-210-0000003', 'user123!', 'USER', date '1993-03-22', 'FEMALE', 'Greece', 'Athens', 'Akti Miaouli 51', 'Citizen', null, 37.941640, 23.652390, now(), now()),
  ('simple_user_3', 'Giorgos', 'Kostas', '+30-210-0000004', 'user123!', 'USER', date '1989-07-19', 'MALE', 'Greece', 'Marousi', 'Kifisias 80', 'Citizen', null, 38.045500, 23.805500, now(), now()),
  ('simple_user_4', 'Maria', 'Antonopoulou', '+30-210-0000005', 'user123!', 'USER', date '1999-11-05', 'FEMALE', 'Greece', 'Glyfada', 'Poseidonos 22', 'Citizen', null, 37.864000, 23.748000, now(), now()),
  ('volunteer_maria', 'Maria', 'Dimitriou', '+30-210-0000006', 'vol123!', 'VOLUNTEER', date '1995-10-08', 'FEMALE', 'Greece', 'Athens', 'Kifisias Ave 25', 'Volunteer Firefighter', 'FIREFIGHTER', 38.025170, 23.793410, now(), now()),
  ('volunteer_nikos', 'Nikos', 'Alexiou', '+30-210-0000007', 'vol123!', 'VOLUNTEER', date '1991-12-14', 'MALE', 'Greece', 'Peristeri', 'Ethnikis Antistaseos 9', 'Volunteer Responder', 'DRIVER', 38.015390, 23.691870, now(), now()),
  ('volunteer_alex', 'Alex', 'Petrou', '+30-210-0000008', 'vol123!', 'VOLUNTEER', date '1994-04-20', 'MALE', 'Greece', 'Kallithea', 'Thiseos 54', 'Volunteer Driver', 'DRIVER', 37.960250, 23.697600, now(), now()),
  ('volunteer_eleni', 'Eleni', 'Sarris', '+30-210-0000009', 'vol123!', 'VOLUNTEER', date '1996-08-28', 'FEMALE', 'Greece', 'Nikaia', 'Petrou Ralli 18', 'Volunteer Firefighter', 'FIREFIGHTER', 37.970900, 23.640600, now(), now())
on conflict (username) do update set
  first_name = excluded.first_name,
  last_name = excluded.last_name,
  telephone = excluded.telephone,
  password = excluded.password,
  user_type = excluded.user_type,
  birthdate = excluded.birthdate,
  gender = excluded.gender,
  country = excluded.country,
  municipality = excluded.municipality,
  address = excluded.address,
  job = excluded.job,
  volunteer_role = excluded.volunteer_role,
  lat = excluded.lat,
  lon = excluded.lon,
  updated_at = now();

-- -------------------------------------------------------------------
-- Seed incidents: 3 fixed + 25 generated (INC-2001..INC-2025)
-- -------------------------------------------------------------------
insert into incidents (incident_code, title, description, status, priority, location, lat, lon, needed_drivers, needed_firefighters, created_by, created_at, updated_at)
select
  'INC-1001',
  'Warehouse Smoke Alert',
  'Smoke reported from a storage warehouse.',
  'active',
  'high',
  'Metaxourgeio, Athens',
  37.984900,
  23.718100,
  2,
  4,
  (select id from users where username = 'admin'),
  now(),
  now()
where not exists (select 1 from incidents where incident_code = 'INC-1001');

insert into incidents (incident_code, title, description, status, priority, location, lat, lon, needed_drivers, needed_firefighters, created_by, created_at, updated_at)
select
  'INC-1002',
  'Forest Edge Fire',
  'Small fire near forest edge.',
  'active',
  'medium',
  'Dionysos, Attica',
  38.108400,
  23.889200,
  1,
  6,
  (select id from users where username = 'admin'),
  now(),
  now()
where not exists (select 1 from incidents where incident_code = 'INC-1002');

insert into incidents (incident_code, title, description, status, priority, location, lat, lon, needed_drivers, needed_firefighters, created_by, created_at, updated_at)
select
  'INC-1003',
  'Minor Vehicle Fire',
  'Vehicle fire resolved with no injuries.',
  'resolved',
  'low',
  'Nea Smyrni, Athens',
  37.947600,
  23.713900,
  1,
  2,
  (select id from users where username = 'admin'),
  now() - interval '72 hours',
  now() - interval '71 hours'
where not exists (select 1 from incidents where incident_code = 'INC-1003');

insert into incidents (incident_code, title, description, status, priority, location, lat, lon, needed_drivers, needed_firefighters, created_by, created_at, updated_at)
select
  'INC-' || (2000 + gs)::text,
  'Test Incident ' || gs::text,
  'Generated incident #' || gs::text || ' for dashboard and map testing.',
  case
    when (gs % 7) = 0 then 'requested'
    when (gs % 3) = 0 then 'resolved'
    else 'active'
  end,
  case
    when (gs % 4) = 0 then 'high'
    when (gs % 2) = 0 then 'medium'
    else 'low'
  end,
  'Sector ' || gs::text || ', Athens',
  37.900000 + (gs * 0.004000),
  23.600000 + (gs * 0.005000),
  (1 + (gs % 3)),
  (2 + (gs % 5)),
  case
    when (gs % 9) = 0 then (select id from users where username = 'simple_user_1')
    when (gs % 8) = 0 then (select id from users where username = 'simple_user_2')
    else (select id from users where username = 'admin')
  end,
  now() - (gs * interval '1 hour'),
  now() - ((gs - 1) * interval '1 hour')
from generate_series(1, 25) gs
where not exists (
  select 1
  from incidents i
  where i.incident_code = 'INC-' || (2000 + gs)::text
);

-- -------------------------------------------------------------------
-- Seed participants (>= 25)
-- -------------------------------------------------------------------
with inc as (
  select
    id,
    incident_code,
    row_number() over (order by incident_code) as rn
  from incidents
  where incident_code like 'INC-20%'
  order by incident_code
  limit 25
),
u as (
  select
    (select id from users where username = 'volunteer_maria') as volunteer_maria,
    (select id from users where username = 'volunteer_nikos') as volunteer_nikos,
    (select id from users where username = 'volunteer_alex') as volunteer_alex,
    (select id from users where username = 'volunteer_eleni') as volunteer_eleni,
    (select id from users where username = 'simple_user_1') as simple_user_1
),
rows as (
  select
    i.id as incident_id,
    case
      when (row_number() over (order by i.incident_code) % 5) = 0 then (select simple_user_1 from u)
      when (row_number() over (order by i.incident_code) % 4) = 0 then (select volunteer_alex from u)
      when (row_number() over (order by i.incident_code) % 3) = 0 then (select volunteer_eleni from u)
      when (row_number() over (order by i.incident_code) % 2) = 0 then (select volunteer_nikos from u)
      else (select volunteer_maria from u)
    end as user_id,
    case
      when (row_number() over (order by i.incident_code) % 2) = 0 then 'Driver'
      else 'Firefighter'
    end as role,
    now() - ((row_number() over (order by i.incident_code)) * interval '30 minutes') as joined_at
  from inc i
)
insert into participants (incident_id, user_id, role, joined_at)
select r.incident_id, r.user_id, r.role, r.joined_at
from rows r
where not exists (
  select 1
  from participants p
  where p.incident_id = r.incident_id and p.user_id = r.user_id
);

-- add a second participant to the first 25 incidents (so the table is comfortably > 25 rows)
with inc as (
  select id, incident_code
  from incidents
  where incident_code like 'INC-20%'
  order by incident_code
  limit 25
),
u as (
  select
    (select id from users where username = 'volunteer_maria') as volunteer_maria,
    (select id from users where username = 'volunteer_nikos') as volunteer_nikos,
    (select id from users where username = 'volunteer_alex') as volunteer_alex
),
rows as (
  select
    i.id as incident_id,
    case
      when (row_number() over (order by i.incident_code) % 3) = 0 then (select volunteer_alex from u)
      when (row_number() over (order by i.incident_code) % 2) = 0 then (select volunteer_nikos from u)
      else (select volunteer_maria from u)
    end as user_id,
    case
      when (row_number() over (order by i.incident_code) % 2) = 0 then 'Firefighter'
      else 'Driver'
    end as role,
    now() - ((row_number() over (order by i.incident_code)) * interval '45 minutes') as joined_at
  from inc i
)
insert into participants (incident_id, user_id, role, joined_at)
select r.incident_id, r.user_id, r.role, r.joined_at
from rows r
where not exists (
  select 1
  from participants p
  where p.incident_id = r.incident_id and p.user_id = r.user_id
);

-- -------------------------------------------------------------------
-- Seed participant requests (25)
-- -------------------------------------------------------------------
with inc as (
  select id, incident_code
  from incidents
  where incident_code like 'INC-20%'
  order by incident_code
  limit 25
),
u as (
  select
    (select id from users where username = 'admin') as admin_id,
    (select id from users where username = 'simple_user_1') as simple_user_1,
    (select id from users where username = 'simple_user_2') as simple_user_2,
    (select id from users where username = 'simple_user_3') as simple_user_3,
    (select id from users where username = 'simple_user_4') as simple_user_4
),
rows as (
  select
    i.id as incident_id,
    case
      when (row_number() over (order by i.incident_code) % 4) = 0 then (select simple_user_4 from u)
      when (row_number() over (order by i.incident_code) % 3) = 0 then (select simple_user_3 from u)
      when (row_number() over (order by i.incident_code) % 2) = 0 then (select simple_user_2 from u)
      else (select simple_user_1 from u)
    end as user_id,
    case
      when (row_number() over (order by i.incident_code) % 2) = 0 then 'DRIVER'
      else 'FIREFIGHTER'
    end as requested_role,
    case
      when (row_number() over (order by i.incident_code) % 5) = 0 then 'rejected'
      when (row_number() over (order by i.incident_code) % 3) = 0 then 'approved'
      else 'requested'
    end as status,
    now() - ((row_number() over (order by i.incident_code)) * interval '2 hours') as created_at,
    case
      when (row_number() over (order by i.incident_code) % 3) = 0 or (row_number() over (order by i.incident_code) % 5) = 0
        then now() - ((row_number() over (order by i.incident_code)) * interval '90 minutes')
      else null
    end as decided_at,
    case
      when (row_number() over (order by i.incident_code) % 3) = 0 or (row_number() over (order by i.incident_code) % 5) = 0
        then (select admin_id from u)
      else null
    end as decided_by
  from inc i
)
insert into participant_requests (incident_id, user_id, requested_role, status, created_at, decided_at, decided_by)
select r.incident_id, r.user_id, r.requested_role, r.status, r.created_at, r.decided_at, r.decided_by
from rows r
where not exists (
  select 1
  from participant_requests pr
  where pr.incident_id = r.incident_id and pr.user_id = r.user_id and pr.requested_role = r.requested_role
);

-- -------------------------------------------------------------------
-- Seed messages (>= 25)
-- -------------------------------------------------------------------
with inc as (
  select
    id,
    incident_code,
    row_number() over (order by incident_code) as rn
  from incidents
  where incident_code like 'INC-20%'
  order by incident_code
  limit 25
),
u as (
  select
    (select id from users where username = 'admin') as admin_id,
    (select id from users where username = 'simple_user_1') as simple_user_1,
    (select id from users where username = 'simple_user_2') as simple_user_2
)
insert into messages (incident_id, sender_id, receiver_id, title, content, message_type, priority, created_at)
select
  i.id,
  (select admin_id from u),
  case when (i.rn % 4) = 0 then (select simple_user_2 from u) else null end,
  case when (i.rn % 4) = 0 then 'Private note for ' || i.incident_code else 'Update for ' || i.incident_code end,
  case when (i.rn % 4) = 0 then 'Please confirm availability for this response.' else 'Response teams assigned and monitoring scene.' end,
  case when (i.rn % 4) = 0 then 'private' else 'public' end,
  case when (i.rn % 6) = 0 then 'high' else 'normal' end,
  now() - (i.rn * interval '75 minutes')
from inc i
where not exists (
  select 1
  from messages m
  where m.incident_id = i.id and m.title = (case when (i.rn % 4) = 0 then 'Private note for ' || i.incident_code else 'Update for ' || i.incident_code end)
);

-- add 10 extra public messages across incidents
with inc as (
  select id, incident_code
  from incidents
  where incident_code like 'INC-20%'
  order by incident_code
  limit 10
),
u as (
  select
    (select id from users where username = 'simple_user_1') as simple_user_1
)
insert into messages (incident_id, sender_id, receiver_id, title, content, message_type, priority, created_at)
select
  i.id,
  (select simple_user_1 from u),
  null,
  'Status ping ' || i.incident_code,
  'Any updates from the field?',
  'public',
  'normal',
  now() - ((row_number() over (order by i.incident_code)) * interval '40 minutes')
from inc i
where not exists (
  select 1
  from messages m
  where m.incident_id = i.id and m.title = 'Status ping ' || i.incident_code
);

-- -------------------------------------------------------------------
-- Seed notification reads (>= 25)
-- -------------------------------------------------------------------
with u as (
  select id, username
  from users
),
g as (
  select generate_series(1, 3) as n
)
insert into notification_reads (user_id, notification_id, read_at)
select
  u.id,
  'notif-' || u.username || '-' || g.n::text,
  now() - ((u.id % 10 + g.n) * interval '3 hours')
from u
cross join g
where not exists (
  select 1
  from notification_reads nr
  where nr.user_id = u.id and nr.notification_id = ('notif-' || u.username || '-' || g.n::text)
);

-- -------------------------------------------------------------------
-- Keep participation roles healthy
-- -------------------------------------------------------------------
update participants
set role = case
  when upper(role) = 'DRIVER' then 'Driver'
  when upper(role) = 'FIREFIGHTER' then 'Firefighter'
  else role
end
where role is not null;

delete from participants
where role is null or upper(role) not in ('FIREFIGHTER','DRIVER');

update participant_requests
set requested_role = upper(requested_role)
where requested_role is not null;

delete from participant_requests
where requested_role is null or upper(requested_role) not in ('FIREFIGHTER','DRIVER');

commit;
